# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'baseOyyder.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(817, 551)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.contenedor_contenedores = QFrame(self.centralwidget)
        self.contenedor_contenedores.setObjectName(u"contenedor_contenedores")
        self.contenedor_contenedores.setMinimumSize(QSize(0, 0))
        self.contenedor_contenedores.setMaximumSize(QSize(0, 16777215))
        self.contenedor_contenedores.setFrameShape(QFrame.StyledPanel)
        self.contenedor_contenedores.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.contenedor_contenedores)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.frm_contnedor_primer_menu = QFrame(self.contenedor_contenedores)
        self.frm_contnedor_primer_menu.setObjectName(u"frm_contnedor_primer_menu")
        self.frm_contnedor_primer_menu.setMinimumSize(QSize(0, 0))
        self.frm_contnedor_primer_menu.setMaximumSize(QSize(90, 16777215))
        self.frm_contnedor_primer_menu.setStyleSheet(u"background-color: rgb(8, 68, 164);")
        self.frm_contnedor_primer_menu.setFrameShape(QFrame.StyledPanel)
        self.frm_contnedor_primer_menu.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frm_contnedor_primer_menu)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frm_primer_menu = QFrame(self.frm_contnedor_primer_menu)
        self.frm_primer_menu.setObjectName(u"frm_primer_menu")
        self.frm_primer_menu.setMinimumSize(QSize(0, 0))
        self.frm_primer_menu.setFrameShape(QFrame.StyledPanel)
        self.frm_primer_menu.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frm_primer_menu)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frm_botonera = QFrame(self.frm_primer_menu)
        self.frm_botonera.setObjectName(u"frm_botonera")
        self.frm_botonera.setFrameShape(QFrame.StyledPanel)
        self.frm_botonera.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frm_botonera)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.frm_cont_home = QWidget(self.frm_botonera)
        self.frm_cont_home.setObjectName(u"frm_cont_home")
        self.horizontalLayout_4 = QHBoxLayout(self.frm_cont_home)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btn_home = QPushButton(self.frm_cont_home)
        self.btn_home.setObjectName(u"btn_home")
        icon = QIcon()
        icon.addFile(u":/icons/icons/house.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_home.setIcon(icon)
        self.btn_home.setIconSize(QSize(32, 50))
        self.btn_home.setCheckable(False)
        self.btn_home.setAutoRepeat(False)
        self.btn_home.setFlat(True)

        self.horizontalLayout_4.addWidget(self.btn_home)


        self.verticalLayout_3.addWidget(self.frm_cont_home)

        self.frm_cont_add = QWidget(self.frm_botonera)
        self.frm_cont_add.setObjectName(u"frm_cont_add")
        self.verticalLayout_5 = QVBoxLayout(self.frm_cont_add)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.btn_add = QPushButton(self.frm_cont_add)
        self.btn_add.setObjectName(u"btn_add")
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/follow.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_add.setIcon(icon1)
        self.btn_add.setIconSize(QSize(32, 50))
        self.btn_add.setFlat(True)

        self.verticalLayout_5.addWidget(self.btn_add)


        self.verticalLayout_3.addWidget(self.frm_cont_add)


        self.verticalLayout_2.addWidget(self.frm_botonera)

        self.frm_botonera2 = QFrame(self.frm_primer_menu)
        self.frm_botonera2.setObjectName(u"frm_botonera2")
        self.frm_botonera2.setFrameShape(QFrame.StyledPanel)
        self.frm_botonera2.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.frm_botonera2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.frm_cont_ges = QWidget(self.frm_botonera2)
        self.frm_cont_ges.setObjectName(u"frm_cont_ges")
        self.verticalLayout_6 = QVBoxLayout(self.frm_cont_ges)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.btn_gestion = QPushButton(self.frm_cont_ges)
        self.btn_gestion.setObjectName(u"btn_gestion")
        icon2 = QIcon()
        icon2.addFile(u"icons/gestion-de-producto.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_gestion.setIcon(icon2)
        self.btn_gestion.setIconSize(QSize(50, 50))
        self.btn_gestion.setFlat(True)

        self.verticalLayout_6.addWidget(self.btn_gestion)


        self.verticalLayout_4.addWidget(self.frm_cont_ges)

        self.widget_4 = QWidget(self.frm_botonera2)
        self.widget_4.setObjectName(u"widget_4")

        self.verticalLayout_4.addWidget(self.widget_4)


        self.verticalLayout_2.addWidget(self.frm_botonera2)

        self.frame_3 = QFrame(self.frm_primer_menu)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.verticalLayout_19 = QVBoxLayout(self.frame_3)
        self.verticalLayout_19.setObjectName(u"verticalLayout_19")
        self.widget_6 = QWidget(self.frame_3)
        self.widget_6.setObjectName(u"widget_6")

        self.verticalLayout_19.addWidget(self.widget_6)

        self.widget_7 = QWidget(self.frame_3)
        self.widget_7.setObjectName(u"widget_7")
        self.verticalLayout_20 = QVBoxLayout(self.widget_7)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName(u"verticalLayout_20")
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_19.addWidget(self.widget_7)


        self.verticalLayout_2.addWidget(self.frame_3)


        self.horizontalLayout_3.addWidget(self.frm_primer_menu)


        self.horizontalLayout_9.addWidget(self.frm_contnedor_primer_menu)


        self.horizontalLayout.addWidget(self.contenedor_contenedores)

        self.frm_contenedor_cuerpo = QFrame(self.centralwidget)
        self.frm_contenedor_cuerpo.setObjectName(u"frm_contenedor_cuerpo")
        self.frm_contenedor_cuerpo.setFrameShape(QFrame.StyledPanel)
        self.frm_contenedor_cuerpo.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.frm_contenedor_cuerpo)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frm_cabecera = QFrame(self.frm_contenedor_cuerpo)
        self.frm_cabecera.setObjectName(u"frm_cabecera")
        self.frm_cabecera.setMaximumSize(QSize(16777215, 50))
        self.frm_cabecera.setCursor(QCursor(Qt.ClosedHandCursor))
        self.frm_cabecera.setFrameShape(QFrame.StyledPanel)
        self.frm_cabecera.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.frm_cabecera)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.frm_cabecera)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_6 = QHBoxLayout(self.frame)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.frame_5 = QFrame(self.frame)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_7 = QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.btn_desplegar = QPushButton(self.frame_5)
        self.btn_desplegar.setObjectName(u"btn_desplegar")
        font = QFont()
        font.setKerning(True)
        self.btn_desplegar.setFont(font)
        icon3 = QIcon()
        icon3.addFile(u":/icons/icons/menu.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_desplegar.setIcon(icon3)
        self.btn_desplegar.setIconSize(QSize(32, 24))
        self.btn_desplegar.setFlat(True)

        self.horizontalLayout_7.addWidget(self.btn_desplegar)


        self.horizontalLayout_6.addWidget(self.frame_5, 0, Qt.AlignLeft|Qt.AlignTop)

        self.frame_7 = QFrame(self.frame)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_6.addWidget(self.frame_7)

        self.frame_6 = QFrame(self.frame)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_6.addWidget(self.frame_6)


        self.horizontalLayout_5.addWidget(self.frame)

        self.frame_2 = QFrame(self.frm_cabecera)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_19 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_19.setObjectName(u"horizontalLayout_19")
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.frame_24 = QFrame(self.frame_2)
        self.frame_24.setObjectName(u"frame_24")
        self.frame_24.setFrameShape(QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_19.addWidget(self.frame_24)


        self.horizontalLayout_5.addWidget(self.frame_2)

        self.frm_contenedor_botones_accionn = QFrame(self.frm_cabecera)
        self.frm_contenedor_botones_accionn.setObjectName(u"frm_contenedor_botones_accionn")
        self.frm_contenedor_botones_accionn.setMaximumSize(QSize(100, 16777215))
        self.frm_btn_expandd = QWidget(self.frm_contenedor_botones_accionn)
        self.frm_btn_expandd.setObjectName(u"frm_btn_expandd")
        self.frm_btn_expandd.setGeometry(QRect(34, 0, 33, 32))
        self.verticalLayout_37 = QVBoxLayout(self.frm_btn_expandd)
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName(u"verticalLayout_37")
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.frm_btn_minii = QWidget(self.frm_btn_expandd)
        self.frm_btn_minii.setObjectName(u"frm_btn_minii")
        self.verticalLayout_36 = QVBoxLayout(self.frm_btn_minii)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName(u"verticalLayout_36")
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.btn_minii = QPushButton(self.frm_btn_minii)
        self.btn_minii.setObjectName(u"btn_minii")
        icon4 = QIcon()
        icon4.addFile(u":/icons/icons/minimize.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_minii.setIcon(icon4)
        self.btn_minii.setIconSize(QSize(24, 24))
        self.btn_minii.setFlat(True)

        self.verticalLayout_36.addWidget(self.btn_minii)


        self.verticalLayout_37.addWidget(self.frm_btn_minii)

        self.frm_btn_cerrarr = QWidget(self.frm_contenedor_botones_accionn)
        self.frm_btn_cerrarr.setObjectName(u"frm_btn_cerrarr")
        self.frm_btn_cerrarr.setGeometry(QRect(67, 0, 33, 32))
        self.verticalLayout_38 = QVBoxLayout(self.frm_btn_cerrarr)
        self.verticalLayout_38.setSpacing(0)
        self.verticalLayout_38.setObjectName(u"verticalLayout_38")
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.btn_cerrarr = QPushButton(self.frm_btn_cerrarr)
        self.btn_cerrarr.setObjectName(u"btn_cerrarr")
        icon5 = QIcon()
        icon5.addFile(u":/icons/icons/delete.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_cerrarr.setIcon(icon5)
        self.btn_cerrarr.setIconSize(QSize(32, 32))
        self.btn_cerrarr.setFlat(True)

        self.verticalLayout_38.addWidget(self.btn_cerrarr)


        self.horizontalLayout_5.addWidget(self.frm_contenedor_botones_accionn)


        self.verticalLayout.addWidget(self.frm_cabecera)

        self.frm_centro = QWidget(self.frm_contenedor_cuerpo)
        self.frm_centro.setObjectName(u"frm_centro")
        self.horizontalLayout_8 = QHBoxLayout(self.frm_centro)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.frm_centrado = QFrame(self.frm_centro)
        self.frm_centrado.setObjectName(u"frm_centrado")
        self.frm_centrado.setFrameShape(QFrame.StyledPanel)
        self.frm_centrado.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_17 = QHBoxLayout(self.frm_centrado)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.frm_botones_seleccion = QFrame(self.frm_centrado)
        self.frm_botones_seleccion.setObjectName(u"frm_botones_seleccion")
        self.frm_botones_seleccion.setFrameShape(QFrame.StyledPanel)
        self.frm_botones_seleccion.setFrameShadow(QFrame.Raised)
        self.verticalLayout_12 = QVBoxLayout(self.frm_botones_seleccion)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.frame_18 = QFrame(self.frm_botones_seleccion)
        self.frame_18.setObjectName(u"frame_18")
        self.frame_18.setMaximumSize(QSize(16777215, 20))
        self.frame_18.setFrameShape(QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QFrame.Raised)

        self.verticalLayout_12.addWidget(self.frame_18)

        self.frm_contenedor_agregar = QFrame(self.frm_botones_seleccion)
        self.frm_contenedor_agregar.setObjectName(u"frm_contenedor_agregar")
        self.frm_contenedor_agregar.setMaximumSize(QSize(0, 16777215))
        self.frm_contenedor_agregar.setStyleSheet(u"background-color: rgb(8, 68, 164);")
        self.frm_contenedor_agregar.setFrameShape(QFrame.StyledPanel)
        self.frm_contenedor_agregar.setFrameShadow(QFrame.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.frm_contenedor_agregar)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.btn_agregar_desplegable = QPushButton(self.frm_contenedor_agregar)
        self.btn_agregar_desplegable.setObjectName(u"btn_agregar_desplegable")
        self.btn_agregar_desplegable.setMinimumSize(QSize(0, 50))
        self.btn_agregar_desplegable.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(8, 68, 164);")
        self.btn_agregar_desplegable.setFlat(True)

        self.verticalLayout_7.addWidget(self.btn_agregar_desplegable)

        self.btn_agregar_desplegable_docente = QPushButton(self.frm_contenedor_agregar)
        self.btn_agregar_desplegable_docente.setObjectName(u"btn_agregar_desplegable_docente")
        self.btn_agregar_desplegable_docente.setMinimumSize(QSize(0, 50))
        self.btn_agregar_desplegable_docente.setAutoFillBackground(False)
        self.btn_agregar_desplegable_docente.setStyleSheet(u"background-color: rgb(8, 68, 164);\n"
"color: rgb(255, 255, 255);")
        self.btn_agregar_desplegable_docente.setFlat(True)

        self.verticalLayout_7.addWidget(self.btn_agregar_desplegable_docente)


        self.verticalLayout_12.addWidget(self.frm_contenedor_agregar)

        self.frm_contenedor_gestionar_pri = QFrame(self.frm_botones_seleccion)
        self.frm_contenedor_gestionar_pri.setObjectName(u"frm_contenedor_gestionar_pri")
        self.frm_contenedor_gestionar_pri.setMaximumSize(QSize(0, 16777215))
        self.frm_contenedor_gestionar_pri.setStyleSheet(u"background-color: rgb(8, 68, 164);")
        self.verticalLayout_8 = QVBoxLayout(self.frm_contenedor_gestionar_pri)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.btn_gestionar_alumnos_desplegable = QPushButton(self.frm_contenedor_gestionar_pri)
        self.btn_gestionar_alumnos_desplegable.setObjectName(u"btn_gestionar_alumnos_desplegable")
        self.btn_gestionar_alumnos_desplegable.setMinimumSize(QSize(0, 0))
        self.btn_gestionar_alumnos_desplegable.setMaximumSize(QSize(16777215, 50))
        self.btn_gestionar_alumnos_desplegable.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.btn_gestionar_alumnos_desplegable.setFlat(True)

        self.verticalLayout_8.addWidget(self.btn_gestionar_alumnos_desplegable)

        self.btn_gestionar_docentes_desplegable = QPushButton(self.frm_contenedor_gestionar_pri)
        self.btn_gestionar_docentes_desplegable.setObjectName(u"btn_gestionar_docentes_desplegable")
        self.btn_gestionar_docentes_desplegable.setMaximumSize(QSize(16777215, 50))
        self.btn_gestionar_docentes_desplegable.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.btn_gestionar_docentes_desplegable.setFlat(True)

        self.verticalLayout_8.addWidget(self.btn_gestionar_docentes_desplegable)


        self.verticalLayout_12.addWidget(self.frm_contenedor_gestionar_pri)

        self.frame_8 = QFrame(self.frm_botones_seleccion)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.verticalLayout_14 = QVBoxLayout(self.frame_8)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")

        self.verticalLayout_12.addWidget(self.frame_8)

        self.frame_17 = QFrame(self.frm_botones_seleccion)
        self.frame_17.setObjectName(u"frame_17")
        self.frame_17.setFrameShape(QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QFrame.Raised)

        self.verticalLayout_12.addWidget(self.frame_17)


        self.horizontalLayout_17.addWidget(self.frm_botones_seleccion)

        self.paginas = QWidget(self.frm_centrado)
        self.paginas.setObjectName(u"paginas")
        self.paginas.setMaximumSize(QSize(10000000, 16777215))
        self.horizontalLayout_2 = QHBoxLayout(self.paginas)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.stw_contenedor_paginas = QStackedWidget(self.paginas)
        self.stw_contenedor_paginas.setObjectName(u"stw_contenedor_paginas")
        self.stw_contenedor_paginas.setStyleSheet(u"background-color: rgb(247, 246, 246);")
        self.pg_home = QWidget()
        self.pg_home.setObjectName(u"pg_home")
        self.horizontalLayout_23 = QHBoxLayout(self.pg_home)
        self.horizontalLayout_23.setObjectName(u"horizontalLayout_23")
        self.frame_9 = QFrame(self.pg_home)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setStyleSheet(u"background-color: rgb(247, 246, 246);")
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.verticalLayout_11 = QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.frame_4 = QFrame(self.frame_9)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setMaximumSize(QSize(16777215, 150))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_12 = QHBoxLayout(self.frame_4)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.frame_13 = QFrame(self.frame_4)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setFrameShape(QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_12.addWidget(self.frame_13)

        self.frame_12 = QFrame(self.frame_4)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setFrameShape(QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.verticalLayout_10 = QVBoxLayout(self.frame_12)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.label = QLabel(self.frame_12)
        self.label.setObjectName(u"label")

        self.verticalLayout_10.addWidget(self.label)


        self.horizontalLayout_12.addWidget(self.frame_12, 0, Qt.AlignVCenter)

        self.frame_10 = QFrame(self.frame_4)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setMaximumSize(QSize(16777215, 300))
        self.frame_10.setStyleSheet(u"image: url(:/icons/icons/logo.png);")
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_12.addWidget(self.frame_10)


        self.verticalLayout_11.addWidget(self.frame_4)

        self.widget_3 = QWidget(self.frame_9)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setMaximumSize(QSize(16777215, 100))

        self.verticalLayout_11.addWidget(self.widget_3)

        self.widget_2 = QWidget(self.frame_9)
        self.widget_2.setObjectName(u"widget_2")
        self.horizontalLayout_11 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.frame_16 = QFrame(self.widget_2)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setMaximumSize(QSize(300, 16777215))
        self.frame_16.setFrameShape(QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_11.addWidget(self.frame_16)

        self.frame_15 = QFrame(self.widget_2)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.verticalLayout_22 = QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName(u"verticalLayout_22")
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.frame_23 = QFrame(self.frame_15)
        self.frame_23.setObjectName(u"frame_23")
        self.frame_23.setFrameShape(QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QFrame.Raised)

        self.verticalLayout_22.addWidget(self.frame_23)

        self.frame_25 = QFrame(self.frame_15)
        self.frame_25.setObjectName(u"frame_25")
        self.frame_25.setStyleSheet(u"image: url(:/icons/icons/frase_menu_inicio.PNG);")
        self.frame_25.setFrameShape(QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QFrame.Raised)

        self.verticalLayout_22.addWidget(self.frame_25)


        self.horizontalLayout_11.addWidget(self.frame_15)

        self.frame_14 = QFrame(self.widget_2)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.verticalLayout_21 = QVBoxLayout(self.frame_14)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName(u"verticalLayout_21")
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.frame_20 = QFrame(self.frame_14)
        self.frame_20.setObjectName(u"frame_20")
        self.frame_20.setFrameShape(QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QFrame.Raised)

        self.verticalLayout_21.addWidget(self.frame_20)

        self.frame_21 = QFrame(self.frame_14)
        self.frame_21.setObjectName(u"frame_21")
        self.frame_21.setStyleSheet(u"image: url(:/icons/icons/barra_inicio.png);")
        self.frame_21.setFrameShape(QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QFrame.Raised)

        self.verticalLayout_21.addWidget(self.frame_21)


        self.horizontalLayout_11.addWidget(self.frame_14)


        self.verticalLayout_11.addWidget(self.widget_2)


        self.horizontalLayout_23.addWidget(self.frame_9)

        self.stw_contenedor_paginas.addWidget(self.pg_home)
        self.pg_agregar_alumnos = QWidget()
        self.pg_agregar_alumnos.setObjectName(u"pg_agregar_alumnos")
        self.horizontalLayout_36 = QHBoxLayout(self.pg_agregar_alumnos)
        self.horizontalLayout_36.setObjectName(u"horizontalLayout_36")
        self.frame_57 = QFrame(self.pg_agregar_alumnos)
        self.frame_57.setObjectName(u"frame_57")
        self.frame_57.setFrameShape(QFrame.StyledPanel)
        self.frame_57.setFrameShadow(QFrame.Raised)
        self.verticalLayout_23 = QVBoxLayout(self.frame_57)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName(u"verticalLayout_23")
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.frame_61 = QFrame(self.frame_57)
        self.frame_61.setObjectName(u"frame_61")
        self.frame_61.setMaximumSize(QSize(16777215, 100))
        self.frame_61.setFrameShape(QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_37 = QHBoxLayout(self.frame_61)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName(u"horizontalLayout_37")
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.frame_64 = QFrame(self.frame_61)
        self.frame_64.setObjectName(u"frame_64")
        self.frame_64.setFrameShape(QFrame.StyledPanel)
        self.frame_64.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_37.addWidget(self.frame_64)

        self.frame_58 = QFrame(self.frame_61)
        self.frame_58.setObjectName(u"frame_58")
        font1 = QFont()
        font1.setPointSize(9)
        self.frame_58.setFont(font1)
        self.frame_58.setStyleSheet(u"image: url(:/icons/icons/titulo_agregar_estudiantes.PNG);")
        self.frame_58.setFrameShape(QFrame.StyledPanel)
        self.frame_58.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_37.addWidget(self.frame_58)

        self.frame_59 = QFrame(self.frame_61)
        self.frame_59.setObjectName(u"frame_59")
        self.frame_59.setStyleSheet(u"image: url(:/icons/icons/logo.png);")
        self.frame_59.setFrameShape(QFrame.StyledPanel)
        self.frame_59.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_37.addWidget(self.frame_59)


        self.verticalLayout_23.addWidget(self.frame_61)

        self.frame_62 = QFrame(self.frame_57)
        self.frame_62.setObjectName(u"frame_62")
        self.frame_62.setFrameShape(QFrame.StyledPanel)
        self.frame_62.setFrameShadow(QFrame.Raised)
        self.txt_apellidos_estudiantes = QLineEdit(self.frame_62)
        self.txt_apellidos_estudiantes.setObjectName(u"txt_apellidos_estudiantes")
        self.txt_apellidos_estudiantes.setGeometry(QRect(505, 70, 181, 20))
        self.txt_apellidos_estudiantes.setFont(font1)
        self.label_11 = QLabel(self.frame_62)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(115, 60, 61, 31))
        self.label_11.setFont(font1)
        self.label_12 = QLabel(self.frame_62)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(105, 110, 71, 41))
        self.label_12.setFont(font1)
        self.label_14 = QLabel(self.frame_62)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(440, 70, 61, 20))
        self.label_14.setFont(font1)
        self.label_13 = QLabel(self.frame_62)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(120, 170, 61, 21))
        self.label_13.setFont(font1)
        self.rb_hombre_estudiantes = QRadioButton(self.frame_62)
        self.rb_hombre_estudiantes.setObjectName(u"rb_hombre_estudiantes")
        self.rb_hombre_estudiantes.setGeometry(QRect(505, 120, 71, 17))
        self.rb_hombre_estudiantes.setFont(font1)
        self.rb_mujer_estudiantes = QRadioButton(self.frame_62)
        self.rb_mujer_estudiantes.setObjectName(u"rb_mujer_estudiantes")
        self.rb_mujer_estudiantes.setGeometry(QRect(585, 120, 61, 17))
        self.rb_mujer_estudiantes.setFont(font1)
        self.btn_cancelar_estudiantes = QPushButton(self.frame_62)
        self.btn_cancelar_estudiantes.setObjectName(u"btn_cancelar_estudiantes")
        self.btn_cancelar_estudiantes.setGeometry(QRect(475, 220, 101, 31))
        font2 = QFont()
        font2.setFamily(u"Microsoft JhengHei")
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setWeight(75)
        self.btn_cancelar_estudiantes.setFont(font2)
        self.label_16 = QLabel(self.frame_62)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(455, 170, 41, 20))
        self.label_16.setFont(font1)
        self.label_15 = QLabel(self.frame_62)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(455, 120, 41, 20))
        self.label_15.setFont(font1)
        self.txt_nombres_estudiantes = QLineEdit(self.frame_62)
        self.txt_nombres_estudiantes.setObjectName(u"txt_nombres_estudiantes")
        self.txt_nombres_estudiantes.setGeometry(QRect(185, 69, 161, 21))
        self.txt_nombres_estudiantes.setFont(font1)
        self.txt_documento_estudiantes = QLineEdit(self.frame_62)
        self.txt_documento_estudiantes.setObjectName(u"txt_documento_estudiantes")
        self.txt_documento_estudiantes.setGeometry(QRect(185, 120, 161, 20))
        self.txt_documento_estudiantes.setFont(font1)
        self.btn_guardar_estudiantes = QPushButton(self.frame_62)
        self.btn_guardar_estudiantes.setObjectName(u"btn_guardar_estudiantes")
        self.btn_guardar_estudiantes.setGeometry(QRect(245, 220, 101, 31))
        self.btn_guardar_estudiantes.setFont(font2)
        self.cbx_grado_estudiantes = QComboBox(self.frame_62)
        self.cbx_grado_estudiantes.addItem("")
        self.cbx_grado_estudiantes.addItem("")
        self.cbx_grado_estudiantes.addItem("")
        self.cbx_grado_estudiantes.addItem("")
        self.cbx_grado_estudiantes.addItem("")
        self.cbx_grado_estudiantes.addItem("")
        self.cbx_grado_estudiantes.addItem("")
        self.cbx_grado_estudiantes.addItem("")
        self.cbx_grado_estudiantes.addItem("")
        self.cbx_grado_estudiantes.addItem("")
        self.cbx_grado_estudiantes.addItem("")
        self.cbx_grado_estudiantes.setObjectName(u"cbx_grado_estudiantes")
        self.cbx_grado_estudiantes.setGeometry(QRect(505, 170, 111, 20))
        self.cbx_grado_estudiantes.setFont(font1)
        self.txt_telefono_estudiantes = QLineEdit(self.frame_62)
        self.txt_telefono_estudiantes.setObjectName(u"txt_telefono_estudiantes")
        self.txt_telefono_estudiantes.setGeometry(QRect(185, 170, 161, 20))
        self.txt_telefono_estudiantes.setFont(font1)
        self.btn_actualizar_estudiante_2 = QPushButton(self.frame_62)
        self.btn_actualizar_estudiante_2.setObjectName(u"btn_actualizar_estudiante_2")
        self.btn_actualizar_estudiante_2.setGeometry(QRect(365, 220, 91, 31))
        self.btn_actualizar_estudiante_2.setFont(font2)
        self.txt_buscar_estudiante_2 = QLineEdit(self.frame_62)
        self.txt_buscar_estudiante_2.setObjectName(u"txt_buscar_estudiante_2")
        self.txt_buscar_estudiante_2.setGeometry(QRect(295, 10, 201, 31))
        self.txt_buscar_estudiante_2.setFont(font1)
        self.btn_buscar_estudiante_2 = QPushButton(self.frame_62)
        self.btn_buscar_estudiante_2.setObjectName(u"btn_buscar_estudiante_2")
        self.btn_buscar_estudiante_2.setGeometry(QRect(505, 10, 81, 31))
        self.btn_buscar_estudiante_2.setFont(font1)

        self.verticalLayout_23.addWidget(self.frame_62)

        self.frame_63 = QFrame(self.frame_57)
        self.frame_63.setObjectName(u"frame_63")
        self.frame_63.setMaximumSize(QSize(16777215, 100))
        self.frame_63.setFrameShape(QFrame.StyledPanel)
        self.frame_63.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_39 = QHBoxLayout(self.frame_63)
        self.horizontalLayout_39.setSpacing(0)
        self.horizontalLayout_39.setObjectName(u"horizontalLayout_39")
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.frame_67 = QFrame(self.frame_63)
        self.frame_67.setObjectName(u"frame_67")
        self.frame_67.setFrameShape(QFrame.StyledPanel)
        self.frame_67.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_39.addWidget(self.frame_67)

        self.frame_66 = QFrame(self.frame_63)
        self.frame_66.setObjectName(u"frame_66")
        self.frame_66.setFrameShape(QFrame.StyledPanel)
        self.frame_66.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_39.addWidget(self.frame_66)

        self.frame_68 = QFrame(self.frame_63)
        self.frame_68.setObjectName(u"frame_68")
        self.frame_68.setFrameShape(QFrame.StyledPanel)
        self.frame_68.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_39.addWidget(self.frame_68)

        self.frame_65 = QFrame(self.frame_63)
        self.frame_65.setObjectName(u"frame_65")
        self.frame_65.setFrameShape(QFrame.StyledPanel)
        self.frame_65.setFrameShadow(QFrame.Raised)
        self.verticalLayout_26 = QVBoxLayout(self.frame_65)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName(u"verticalLayout_26")
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.frame_60 = QFrame(self.frame_65)
        self.frame_60.setObjectName(u"frame_60")
        self.frame_60.setStyleSheet(u"image: url(:/icons/icons/barra_agregar.PNG);")
        self.frame_60.setFrameShape(QFrame.StyledPanel)
        self.frame_60.setFrameShadow(QFrame.Raised)

        self.verticalLayout_26.addWidget(self.frame_60)


        self.horizontalLayout_39.addWidget(self.frame_65)


        self.verticalLayout_23.addWidget(self.frame_63)


        self.horizontalLayout_36.addWidget(self.frame_57)

        self.stw_contenedor_paginas.addWidget(self.pg_agregar_alumnos)
        self.pg_gestion_docentes = QWidget()
        self.pg_gestion_docentes.setObjectName(u"pg_gestion_docentes")
        self.horizontalLayout_24 = QHBoxLayout(self.pg_gestion_docentes)
        self.horizontalLayout_24.setObjectName(u"horizontalLayout_24")
        self.frame_47 = QFrame(self.pg_gestion_docentes)
        self.frame_47.setObjectName(u"frame_47")
        self.frame_47.setFrameShape(QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QFrame.Raised)
        self.frame_47.setLineWidth(0)
        self.frame_73 = QFrame(self.frame_47)
        self.frame_73.setObjectName(u"frame_73")
        self.frame_73.setGeometry(QRect(440, 10, 5, 467))
        self.frame_73.setMaximumSize(QSize(5, 16777215))
        self.frame_73.setStyleSheet(u"background-color: rgb(8, 68, 164);")
        self.frame_73.setFrameShape(QFrame.StyledPanel)
        self.frame_73.setFrameShadow(QFrame.Raised)
        self.frm_contenedor_modificar_2 = QFrame(self.frame_47)
        self.frm_contenedor_modificar_2.setObjectName(u"frm_contenedor_modificar_2")
        self.frm_contenedor_modificar_2.setGeometry(QRect(450, 0, 250, 230))
        self.frm_contenedor_modificar_2.setMaximumSize(QSize(250, 16777215))
        self.frm_contenedor_modificar_2.setFrameShape(QFrame.StyledPanel)
        self.frm_contenedor_modificar_2.setFrameShadow(QFrame.Raised)
        self.verticalLayout_27 = QVBoxLayout(self.frm_contenedor_modificar_2)
        self.verticalLayout_27.setObjectName(u"verticalLayout_27")
        self.frame_75 = QFrame(self.frm_contenedor_modificar_2)
        self.frame_75.setObjectName(u"frame_75")
        self.frame_75.setFrameShape(QFrame.StyledPanel)
        self.frame_75.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_40 = QHBoxLayout(self.frame_75)
        self.horizontalLayout_40.setSpacing(0)
        self.horizontalLayout_40.setObjectName(u"horizontalLayout_40")
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.frame_76 = QFrame(self.frame_75)
        self.frame_76.setObjectName(u"frame_76")
        self.frame_76.setFrameShape(QFrame.StyledPanel)
        self.frame_76.setFrameShadow(QFrame.Raised)
        self.label_18 = QLabel(self.frame_76)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 40, 36, 16))
        self.label_18.setFont(font1)
        self.cbx_edit_grado_doce = QComboBox(self.frame_76)
        self.cbx_edit_grado_doce.addItem("")
        self.cbx_edit_grado_doce.addItem("")
        self.cbx_edit_grado_doce.addItem("")
        self.cbx_edit_grado_doce.addItem("")
        self.cbx_edit_grado_doce.addItem("")
        self.cbx_edit_grado_doce.addItem("")
        self.cbx_edit_grado_doce.addItem("")
        self.cbx_edit_grado_doce.addItem("")
        self.cbx_edit_grado_doce.addItem("")
        self.cbx_edit_grado_doce.addItem("")
        self.cbx_edit_grado_doce.addItem("")
        self.cbx_edit_grado_doce.setObjectName(u"cbx_edit_grado_doce")
        self.cbx_edit_grado_doce.setGeometry(QRect(70, 40, 91, 20))
        self.cbx_edit_grado_doce.setFont(font1)

        self.horizontalLayout_40.addWidget(self.frame_76)


        self.verticalLayout_27.addWidget(self.frame_75)

        self.frame_79 = QFrame(self.frm_contenedor_modificar_2)
        self.frame_79.setObjectName(u"frame_79")
        self.frame_79.setFrameShape(QFrame.StyledPanel)
        self.frame_79.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_44 = QHBoxLayout(self.frame_79)
        self.horizontalLayout_44.setSpacing(0)
        self.horizontalLayout_44.setObjectName(u"horizontalLayout_44")
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, -1)
        self.frame_80 = QFrame(self.frame_79)
        self.frame_80.setObjectName(u"frame_80")
        self.frame_80.setFrameShape(QFrame.StyledPanel)
        self.frame_80.setFrameShadow(QFrame.Raised)
        self.label_20 = QLabel(self.frame_80)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 40, 43, 16))
        self.label_20.setFont(font1)
        self.cbx_edit_materia_doce = QComboBox(self.frame_80)
        self.cbx_edit_materia_doce.addItem("")
        self.cbx_edit_materia_doce.addItem("")
        self.cbx_edit_materia_doce.addItem("")
        self.cbx_edit_materia_doce.addItem("")
        self.cbx_edit_materia_doce.addItem("")
        self.cbx_edit_materia_doce.addItem("")
        self.cbx_edit_materia_doce.addItem("")
        self.cbx_edit_materia_doce.setObjectName(u"cbx_edit_materia_doce")
        self.cbx_edit_materia_doce.setGeometry(QRect(70, 40, 111, 20))
        self.cbx_edit_materia_doce.setFont(font1)

        self.horizontalLayout_44.addWidget(self.frame_80)


        self.verticalLayout_27.addWidget(self.frame_79)

        self.frame_74 = QFrame(self.frame_47)
        self.frame_74.setObjectName(u"frame_74")
        self.frame_74.setGeometry(QRect(460, 230, 230, 145))
        self.frame_74.setMaximumSize(QSize(230, 145))
        self.frame_74.setFrameShape(QFrame.StyledPanel)
        self.frame_74.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame_74)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 62, 46, 16))
        self.label_2.setFont(font1)
        self.lineEdit = QLineEdit(self.frame_74)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(72, 1, 151, 131))
        self.frame_11 = QFrame(self.frame_47)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(0, 0, 441, 471))
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.frame_69 = QFrame(self.frame_11)
        self.frame_69.setObjectName(u"frame_69")
        self.frame_69.setGeometry(QRect(0, 0, 316, 114))
        self.frame_69.setStyleSheet(u"image: url(:/icons/icons/titulo_gestion_estudiantes.PNG);")
        self.frame_69.setFrameShape(QFrame.StyledPanel)
        self.frame_69.setFrameShadow(QFrame.Raised)
        self.frame_70 = QFrame(self.frame_11)
        self.frame_70.setObjectName(u"frame_70")
        self.frame_70.setGeometry(QRect(320, 0, 100, 114))
        self.frame_70.setMaximumSize(QSize(100, 16777215))
        self.frame_70.setStyleSheet(u"image: url(:/icons/icons/logo.png);")
        self.frame_70.setFrameShape(QFrame.StyledPanel)
        self.frame_70.setFrameShadow(QFrame.Raised)
        self.frame_71 = QFrame(self.frame_11)
        self.frame_71.setObjectName(u"frame_71")
        self.frame_71.setGeometry(QRect(0, 110, 421, 115))
        self.frame_71.setFrameShape(QFrame.StyledPanel)
        self.frame_71.setFrameShadow(QFrame.Raised)
        self.txt_buscar_docente = QLineEdit(self.frame_71)
        self.txt_buscar_docente.setObjectName(u"txt_buscar_docente")
        self.txt_buscar_docente.setGeometry(QRect(60, 50, 201, 31))
        self.txt_buscar_docente.setFont(font1)
        self.btn_buscar_docente = QPushButton(self.frame_71)
        self.btn_buscar_docente.setObjectName(u"btn_buscar_docente")
        self.btn_buscar_docente.setGeometry(QRect(290, 50, 81, 31))
        self.btn_buscar_docente.setFont(font1)
        self.frame_72 = QFrame(self.frame_11)
        self.frame_72.setObjectName(u"frame_72")
        self.frame_72.setGeometry(QRect(0, 230, 416, 114))
        self.frame_72.setFrameShape(QFrame.StyledPanel)
        self.frame_72.setFrameShadow(QFrame.Raised)
        self.tbl_info_docente = QTableWidget(self.frame_72)
        if (self.tbl_info_docente.columnCount() < 3):
            self.tbl_info_docente.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.tbl_info_docente.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tbl_info_docente.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tbl_info_docente.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        if (self.tbl_info_docente.rowCount() < 1):
            self.tbl_info_docente.setRowCount(1)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tbl_info_docente.setVerticalHeaderItem(0, __qtablewidgetitem3)
        self.tbl_info_docente.setObjectName(u"tbl_info_docente")
        self.tbl_info_docente.setGeometry(QRect(20, 30, 371, 51))
        font3 = QFont()
        font3.setPointSize(10)
        self.tbl_info_docente.setFont(font3)
        self.frame_77 = QFrame(self.frame_11)
        self.frame_77.setObjectName(u"frame_77")
        self.frame_77.setGeometry(QRect(10, 350, 69, 112))
        self.frame_77.setFrameShape(QFrame.StyledPanel)
        self.frame_77.setFrameShadow(QFrame.Raised)
        self.frame_78 = QFrame(self.frame_11)
        self.frame_78.setObjectName(u"frame_78")
        self.frame_78.setGeometry(QRect(80, 350, 137, 112))
        self.frame_78.setFrameShape(QFrame.StyledPanel)
        self.frame_78.setFrameShadow(QFrame.Raised)
        self.frame_81 = QFrame(self.frame_78)
        self.frame_81.setObjectName(u"frame_81")
        self.frame_81.setGeometry(QRect(10, 10, 16, 92))
        self.frame_81.setFrameShape(QFrame.StyledPanel)
        self.frame_81.setFrameShadow(QFrame.Raised)
        self.btn_guardar_docente_2 = QPushButton(self.frame_78)
        self.btn_guardar_docente_2.setObjectName(u"btn_guardar_docente_2")
        self.btn_guardar_docente_2.setGeometry(QRect(26, 36, 91, 31))
        self.btn_guardar_docente_2.setFont(font2)
        self.frame_83 = QFrame(self.frame_11)
        self.frame_83.setObjectName(u"frame_83")
        self.frame_83.setGeometry(QRect(220, 350, 131, 112))
        self.frame_83.setFrameShape(QFrame.StyledPanel)
        self.frame_83.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_27 = QHBoxLayout(self.frame_83)
        self.horizontalLayout_27.setObjectName(u"horizontalLayout_27")
        self.frame_85 = QFrame(self.frame_83)
        self.frame_85.setObjectName(u"frame_85")
        self.frame_85.setFrameShape(QFrame.StyledPanel)
        self.frame_85.setFrameShadow(QFrame.Raised)
        self.btn_eliminar_docente = QPushButton(self.frame_85)
        self.btn_eliminar_docente.setObjectName(u"btn_eliminar_docente")
        self.btn_eliminar_docente.setGeometry(QRect(10, 26, 81, 31))
        self.btn_eliminar_docente.setFont(font2)

        self.horizontalLayout_27.addWidget(self.frame_85)

        self.frame_86 = QFrame(self.frame_11)
        self.frame_86.setObjectName(u"frame_86")
        self.frame_86.setGeometry(QRect(350, 350, 75, 112))
        self.frame_86.setFrameShape(QFrame.StyledPanel)
        self.frame_86.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_24.addWidget(self.frame_47)

        self.stw_contenedor_paginas.addWidget(self.pg_gestion_docentes)
        self.pg_gestion_alumnos = QWidget()
        self.pg_gestion_alumnos.setObjectName(u"pg_gestion_alumnos")
        self.horizontalLayout_13 = QHBoxLayout(self.pg_gestion_alumnos)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.frame_26 = QFrame(self.pg_gestion_alumnos)
        self.frame_26.setObjectName(u"frame_26")
        self.frame_26.setFrameShape(QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QFrame.Raised)
        self.verticalLayout_24 = QVBoxLayout(self.frame_26)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName(u"verticalLayout_24")
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.frame_33 = QFrame(self.frame_26)
        self.frame_33.setObjectName(u"frame_33")
        self.frame_33.setFrameShape(QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_16 = QHBoxLayout(self.frame_33)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.frame_31 = QFrame(self.frame_33)
        self.frame_31.setObjectName(u"frame_31")
        self.frame_31.setStyleSheet(u"image: url(:/icons/icons/titulo_gestion_estudiantes.PNG);")
        self.frame_31.setFrameShape(QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_16.addWidget(self.frame_31)

        self.frame_30 = QFrame(self.frame_33)
        self.frame_30.setObjectName(u"frame_30")
        self.frame_30.setMaximumSize(QSize(100, 16777215))
        self.frame_30.setStyleSheet(u"image: url(:/icons/icons/logo.png);")
        self.frame_30.setFrameShape(QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_16.addWidget(self.frame_30)


        self.verticalLayout_24.addWidget(self.frame_33)

        self.frame_27 = QFrame(self.frame_26)
        self.frame_27.setObjectName(u"frame_27")
        self.frame_27.setFrameShape(QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_14 = QHBoxLayout(self.frame_27)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.frame_35 = QFrame(self.frame_27)
        self.frame_35.setObjectName(u"frame_35")
        self.frame_35.setFrameShape(QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QFrame.Raised)
        self.txt_buscar_estudiante = QLineEdit(self.frame_35)
        self.txt_buscar_estudiante.setObjectName(u"txt_buscar_estudiante")
        self.txt_buscar_estudiante.setGeometry(QRect(60, 60, 201, 31))
        self.txt_buscar_estudiante.setFont(font1)
        self.btn_buscar_estudiante = QPushButton(self.frame_35)
        self.btn_buscar_estudiante.setObjectName(u"btn_buscar_estudiante")
        self.btn_buscar_estudiante.setGeometry(QRect(284, 60, 81, 31))
        self.btn_buscar_estudiante.setFont(font1)

        self.horizontalLayout_14.addWidget(self.frame_35)

        self.frame_36 = QFrame(self.frame_27)
        self.frame_36.setObjectName(u"frame_36")
        self.frame_36.setMaximumSize(QSize(0, 16777215))
        self.frame_36.setFrameShape(QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_14.addWidget(self.frame_36)


        self.verticalLayout_24.addWidget(self.frame_27)

        self.frame_28 = QFrame(self.frame_26)
        self.frame_28.setObjectName(u"frame_28")
        self.frame_28.setFrameShape(QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_15 = QHBoxLayout(self.frame_28)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.frame_34 = QFrame(self.frame_28)
        self.frame_34.setObjectName(u"frame_34")
        self.frame_34.setFrameShape(QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QFrame.Raised)
        self.tbl_info_estudiante = QTableWidget(self.frame_34)
        if (self.tbl_info_estudiante.columnCount() < 3):
            self.tbl_info_estudiante.setColumnCount(3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tbl_info_estudiante.setHorizontalHeaderItem(0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tbl_info_estudiante.setHorizontalHeaderItem(1, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tbl_info_estudiante.setHorizontalHeaderItem(2, __qtablewidgetitem6)
        if (self.tbl_info_estudiante.rowCount() < 1):
            self.tbl_info_estudiante.setRowCount(1)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tbl_info_estudiante.setVerticalHeaderItem(0, __qtablewidgetitem7)
        self.tbl_info_estudiante.setObjectName(u"tbl_info_estudiante")
        self.tbl_info_estudiante.setGeometry(QRect(20, 30, 371, 51))

        self.horizontalLayout_15.addWidget(self.frame_34)


        self.verticalLayout_24.addWidget(self.frame_28)

        self.frame_29 = QFrame(self.frame_26)
        self.frame_29.setObjectName(u"frame_29")
        self.frame_29.setFrameShape(QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_20 = QHBoxLayout(self.frame_29)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.frame_37 = QFrame(self.frame_29)
        self.frame_37.setObjectName(u"frame_37")
        self.frame_37.setFrameShape(QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_21 = QHBoxLayout(self.frame_37)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName(u"horizontalLayout_21")
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.frame_39 = QFrame(self.frame_37)
        self.frame_39.setObjectName(u"frame_39")
        self.frame_39.setFrameShape(QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_21.addWidget(self.frame_39)

        self.frame_40 = QFrame(self.frame_37)
        self.frame_40.setObjectName(u"frame_40")
        self.frame_40.setFrameShape(QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QFrame.Raised)
        self.btn_guardar_estudiantes_ges = QPushButton(self.frame_40)
        self.btn_guardar_estudiantes_ges.setObjectName(u"btn_guardar_estudiantes_ges")
        self.btn_guardar_estudiantes_ges.setGeometry(QRect(0, 40, 91, 31))
        font4 = QFont()
        font4.setFamily(u"Microsoft JhengHei UI")
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setWeight(75)
        self.btn_guardar_estudiantes_ges.setFont(font4)

        self.horizontalLayout_21.addWidget(self.frame_40)


        self.horizontalLayout_20.addWidget(self.frame_37)

        self.frame_38 = QFrame(self.frame_29)
        self.frame_38.setObjectName(u"frame_38")
        self.frame_38.setFrameShape(QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_22 = QHBoxLayout(self.frame_38)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName(u"horizontalLayout_22")
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.frame_42 = QFrame(self.frame_38)
        self.frame_42.setObjectName(u"frame_42")
        self.frame_42.setFrameShape(QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QFrame.Raised)
        self.btn_eliminar_estudiante_ges = QPushButton(self.frame_42)
        self.btn_eliminar_estudiante_ges.setObjectName(u"btn_eliminar_estudiante_ges")
        self.btn_eliminar_estudiante_ges.setGeometry(QRect(0, 40, 91, 31))
        self.btn_eliminar_estudiante_ges.setFont(font2)

        self.horizontalLayout_22.addWidget(self.frame_42)

        self.frame_41 = QFrame(self.frame_38)
        self.frame_41.setObjectName(u"frame_41")
        self.frame_41.setFrameShape(QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_22.addWidget(self.frame_41)


        self.horizontalLayout_20.addWidget(self.frame_38)


        self.verticalLayout_24.addWidget(self.frame_29)


        self.horizontalLayout_13.addWidget(self.frame_26)

        self.frame_32 = QFrame(self.pg_gestion_alumnos)
        self.frame_32.setObjectName(u"frame_32")
        self.frame_32.setMaximumSize(QSize(5, 16777215))
        self.frame_32.setStyleSheet(u"background-color: rgb(8, 68, 164);")
        self.frame_32.setFrameShape(QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_13.addWidget(self.frame_32)

        self.frm_contenedor_modificar = QFrame(self.pg_gestion_alumnos)
        self.frm_contenedor_modificar.setObjectName(u"frm_contenedor_modificar")
        self.frm_contenedor_modificar.setMaximumSize(QSize(250, 16777215))
        self.frm_contenedor_modificar.setFrameShape(QFrame.StyledPanel)
        self.frm_contenedor_modificar.setFrameShadow(QFrame.Raised)
        self.verticalLayout_25 = QVBoxLayout(self.frm_contenedor_modificar)
        self.verticalLayout_25.setObjectName(u"verticalLayout_25")
        self.frame_55 = QFrame(self.frm_contenedor_modificar)
        self.frame_55.setObjectName(u"frame_55")
        self.frame_55.setFrameShape(QFrame.StyledPanel)
        self.frame_55.setFrameShadow(QFrame.Raised)
        self.label_10 = QLabel(self.frame_55)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 30, 55, 16))
        self.label_10.setFont(font1)
        self.txt_edit_nota_est = QLineEdit(self.frame_55)
        self.txt_edit_nota_est.setObjectName(u"txt_edit_nota_est")
        self.txt_edit_nota_est.setGeometry(QRect(80, 30, 101, 20))
        self.txt_edit_nota_est.setFont(font1)

        self.verticalLayout_25.addWidget(self.frame_55)

        self.frame_48 = QFrame(self.frm_contenedor_modificar)
        self.frame_48.setObjectName(u"frame_48")
        self.frame_48.setFrameShape(QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_29 = QHBoxLayout(self.frame_48)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName(u"horizontalLayout_29")
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.frame_52 = QFrame(self.frame_48)
        self.frame_52.setObjectName(u"frame_52")
        self.frame_52.setFrameShape(QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QFrame.Raised)
        self.label_7 = QLabel(self.frame_52)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 30, 41, 20))
        self.label_7.setFont(font1)
        self.cbx_edit_grado_est = QComboBox(self.frame_52)
        self.cbx_edit_grado_est.addItem("")
        self.cbx_edit_grado_est.addItem("")
        self.cbx_edit_grado_est.addItem("")
        self.cbx_edit_grado_est.addItem("")
        self.cbx_edit_grado_est.addItem("")
        self.cbx_edit_grado_est.addItem("")
        self.cbx_edit_grado_est.addItem("")
        self.cbx_edit_grado_est.addItem("")
        self.cbx_edit_grado_est.addItem("")
        self.cbx_edit_grado_est.addItem("")
        self.cbx_edit_grado_est.addItem("")
        self.cbx_edit_grado_est.setObjectName(u"cbx_edit_grado_est")
        self.cbx_edit_grado_est.setGeometry(QRect(80, 30, 101, 20))
        self.cbx_edit_grado_est.setFont(font1)

        self.horizontalLayout_29.addWidget(self.frame_52)


        self.verticalLayout_25.addWidget(self.frame_48)

        self.frame_49 = QFrame(self.frm_contenedor_modificar)
        self.frame_49.setObjectName(u"frame_49")
        self.frame_49.setFrameShape(QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_31 = QHBoxLayout(self.frame_49)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName(u"horizontalLayout_31")
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.frame_53 = QFrame(self.frame_49)
        self.frame_53.setObjectName(u"frame_53")
        self.frame_53.setFrameShape(QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QFrame.Raised)
        self.label_8 = QLabel(self.frame_53)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 30, 45, 16))
        self.label_8.setFont(font1)
        self.cbx_edit_periodo_est = QComboBox(self.frame_53)
        self.cbx_edit_periodo_est.addItem("")
        self.cbx_edit_periodo_est.addItem("")
        self.cbx_edit_periodo_est.addItem("")
        self.cbx_edit_periodo_est.addItem("")
        self.cbx_edit_periodo_est.setObjectName(u"cbx_edit_periodo_est")
        self.cbx_edit_periodo_est.setGeometry(QRect(80, 30, 101, 21))
        self.cbx_edit_periodo_est.setFont(font1)

        self.horizontalLayout_31.addWidget(self.frame_53)


        self.verticalLayout_25.addWidget(self.frame_49)

        self.frame_51 = QFrame(self.frm_contenedor_modificar)
        self.frame_51.setObjectName(u"frame_51")
        self.frame_51.setFrameShape(QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_33 = QHBoxLayout(self.frame_51)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName(u"horizontalLayout_33")
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, -1)
        self.frame_54 = QFrame(self.frame_51)
        self.frame_54.setObjectName(u"frame_54")
        self.frame_54.setFrameShape(QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QFrame.Raised)
        self.label_9 = QLabel(self.frame_54)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 30, 43, 16))
        self.label_9.setFont(font1)
        self.cbx_edit_materia_est = QComboBox(self.frame_54)
        self.cbx_edit_materia_est.addItem("")
        self.cbx_edit_materia_est.addItem("")
        self.cbx_edit_materia_est.addItem("")
        self.cbx_edit_materia_est.addItem("")
        self.cbx_edit_materia_est.addItem("")
        self.cbx_edit_materia_est.addItem("")
        self.cbx_edit_materia_est.addItem("")
        self.cbx_edit_materia_est.setObjectName(u"cbx_edit_materia_est")
        self.cbx_edit_materia_est.setGeometry(QRect(80, 30, 101, 21))
        self.cbx_edit_materia_est.setFont(font1)

        self.horizontalLayout_33.addWidget(self.frame_54)


        self.verticalLayout_25.addWidget(self.frame_51)

        self.frame_50 = QFrame(self.frm_contenedor_modificar)
        self.frame_50.setObjectName(u"frame_50")
        self.frame_50.setFrameShape(QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_35 = QHBoxLayout(self.frame_50)
        self.horizontalLayout_35.setSpacing(0)
        self.horizontalLayout_35.setObjectName(u"horizontalLayout_35")
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.frame_56 = QFrame(self.frame_50)
        self.frame_56.setObjectName(u"frame_56")
        self.frame_56.setFrameShape(QFrame.StyledPanel)
        self.frame_56.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_35.addWidget(self.frame_56)


        self.verticalLayout_25.addWidget(self.frame_50)


        self.horizontalLayout_13.addWidget(self.frm_contenedor_modificar)

        self.stw_contenedor_paginas.addWidget(self.pg_gestion_alumnos)
        self.pg_agregar_docente = QWidget()
        self.pg_agregar_docente.setObjectName(u"pg_agregar_docente")
        self.frame_43 = QFrame(self.pg_agregar_docente)
        self.frame_43.setObjectName(u"frame_43")
        self.frame_43.setGeometry(QRect(60, 10, 701, 481))
        self.frame_43.setFrameShape(QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QFrame.Raised)
        self.frame_87 = QFrame(self.frame_43)
        self.frame_87.setObjectName(u"frame_87")
        self.frame_87.setGeometry(QRect(0, 0, 229, 98))
        self.frame_87.setFrameShape(QFrame.StyledPanel)
        self.frame_87.setFrameShadow(QFrame.Raised)
        self.frame_88 = QFrame(self.frame_43)
        self.frame_88.setObjectName(u"frame_88")
        self.frame_88.setGeometry(QRect(230, 0, 229, 98))
        self.frame_88.setFrameShape(QFrame.StyledPanel)
        self.frame_88.setFrameShadow(QFrame.Raised)
        self.label_3 = QLabel(self.frame_88)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 20, 201, 51))
        font5 = QFont()
        font5.setFamily(u"Leelawadee UI")
        font5.setPointSize(18)
        font5.setBold(True)
        font5.setWeight(75)
        self.label_3.setFont(font5)
        self.frame_89 = QFrame(self.frame_43)
        self.frame_89.setObjectName(u"frame_89")
        self.frame_89.setGeometry(QRect(460, 0, 229, 98))
        self.frame_89.setStyleSheet(u"image: url(:/icons/icons/logo.png);")
        self.frame_89.setFrameShape(QFrame.StyledPanel)
        self.frame_89.setFrameShadow(QFrame.Raised)
        self.frame_90 = QFrame(self.frame_43)
        self.frame_90.setObjectName(u"frame_90")
        self.frame_90.setGeometry(QRect(10, 100, 690, 271))
        self.frame_90.setFrameShape(QFrame.StyledPanel)
        self.frame_90.setFrameShadow(QFrame.Raised)
        self.txt_apellidos_docente = QLineEdit(self.frame_90)
        self.txt_apellidos_docente.setObjectName(u"txt_apellidos_docente")
        self.txt_apellidos_docente.setGeometry(QRect(430, 70, 181, 20))
        self.txt_apellidos_docente.setFont(font1)
        self.label_17 = QLabel(self.frame_90)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(40, 60, 61, 31))
        self.label_17.setFont(font1)
        self.label_19 = QLabel(self.frame_90)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 110, 71, 41))
        self.label_19.setFont(font1)
        self.label_21 = QLabel(self.frame_90)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(365, 70, 61, 20))
        self.label_21.setFont(font1)
        self.label_22 = QLabel(self.frame_90)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(50, 170, 61, 21))
        self.label_22.setFont(font1)
        self.rb_hombre_docente = QRadioButton(self.frame_90)
        self.rb_hombre_docente.setObjectName(u"rb_hombre_docente")
        self.rb_hombre_docente.setGeometry(QRect(430, 120, 71, 17))
        self.rb_hombre_docente.setFont(font1)
        self.rb_mujer_docente = QRadioButton(self.frame_90)
        self.rb_mujer_docente.setObjectName(u"rb_mujer_docente")
        self.rb_mujer_docente.setGeometry(QRect(510, 120, 61, 17))
        self.rb_mujer_docente.setFont(font1)
        self.btn_cancelar_docente = QPushButton(self.frame_90)
        self.btn_cancelar_docente.setObjectName(u"btn_cancelar_docente")
        self.btn_cancelar_docente.setGeometry(QRect(400, 220, 101, 31))
        self.btn_cancelar_docente.setFont(font2)
        self.label_24 = QLabel(self.frame_90)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(380, 120, 31, 16))
        self.label_24.setFont(font1)
        self.txt_nombres_docente = QLineEdit(self.frame_90)
        self.txt_nombres_docente.setObjectName(u"txt_nombres_docente")
        self.txt_nombres_docente.setGeometry(QRect(110, 69, 161, 21))
        self.txt_nombres_docente.setFont(font1)
        self.txt_documento_docente = QLineEdit(self.frame_90)
        self.txt_documento_docente.setObjectName(u"txt_documento_docente")
        self.txt_documento_docente.setGeometry(QRect(110, 120, 161, 20))
        self.txt_documento_docente.setFont(font1)
        self.btn_guardar_docente = QPushButton(self.frame_90)
        self.btn_guardar_docente.setObjectName(u"btn_guardar_docente")
        self.btn_guardar_docente.setGeometry(QRect(170, 220, 101, 31))
        self.btn_guardar_docente.setFont(font2)
        self.txt_telefono_docente = QLineEdit(self.frame_90)
        self.txt_telefono_docente.setObjectName(u"txt_telefono_docente")
        self.txt_telefono_docente.setGeometry(QRect(110, 170, 161, 20))
        self.txt_telefono_docente.setFont(font1)
        self.btn_actualizar_docente = QPushButton(self.frame_90)
        self.btn_actualizar_docente.setObjectName(u"btn_actualizar_docente")
        self.btn_actualizar_docente.setGeometry(QRect(290, 220, 91, 31))
        self.btn_actualizar_docente.setFont(font2)
        self.txt_buscar_docente_2 = QLineEdit(self.frame_90)
        self.txt_buscar_docente_2.setObjectName(u"txt_buscar_docente_2")
        self.txt_buscar_docente_2.setGeometry(QRect(220, 10, 201, 31))
        self.txt_buscar_docente_2.setFont(font1)
        self.btn_buscar_docente_2 = QPushButton(self.frame_90)
        self.btn_buscar_docente_2.setObjectName(u"btn_buscar_docente_2")
        self.btn_buscar_docente_2.setGeometry(QRect(430, 10, 81, 31))
        self.btn_buscar_docente_2.setFont(font1)
        self.frame_91 = QFrame(self.frame_43)
        self.frame_91.setObjectName(u"frame_91")
        self.frame_91.setGeometry(QRect(0, 380, 690, 100))
        self.frame_91.setMaximumSize(QSize(16777215, 100))
        self.frame_91.setFrameShape(QFrame.StyledPanel)
        self.frame_91.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_41 = QHBoxLayout(self.frame_91)
        self.horizontalLayout_41.setSpacing(0)
        self.horizontalLayout_41.setObjectName(u"horizontalLayout_41")
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.frame_92 = QFrame(self.frame_91)
        self.frame_92.setObjectName(u"frame_92")
        self.frame_92.setFrameShape(QFrame.StyledPanel)
        self.frame_92.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_41.addWidget(self.frame_92)

        self.frame_93 = QFrame(self.frame_91)
        self.frame_93.setObjectName(u"frame_93")
        self.frame_93.setFrameShape(QFrame.StyledPanel)
        self.frame_93.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_41.addWidget(self.frame_93)

        self.frame_94 = QFrame(self.frame_91)
        self.frame_94.setObjectName(u"frame_94")
        self.frame_94.setFrameShape(QFrame.StyledPanel)
        self.frame_94.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_41.addWidget(self.frame_94)

        self.frame_95 = QFrame(self.frame_91)
        self.frame_95.setObjectName(u"frame_95")
        self.frame_95.setFrameShape(QFrame.StyledPanel)
        self.frame_95.setFrameShadow(QFrame.Raised)
        self.verticalLayout_28 = QVBoxLayout(self.frame_95)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName(u"verticalLayout_28")
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.frame_96 = QFrame(self.frame_95)
        self.frame_96.setObjectName(u"frame_96")
        self.frame_96.setStyleSheet(u"image: url(:/icons/icons/barra_agregar.PNG);")
        self.frame_96.setFrameShape(QFrame.StyledPanel)
        self.frame_96.setFrameShadow(QFrame.Raised)

        self.verticalLayout_28.addWidget(self.frame_96)


        self.horizontalLayout_41.addWidget(self.frame_95)

        self.stw_contenedor_paginas.addWidget(self.pg_agregar_docente)

        self.horizontalLayout_2.addWidget(self.stw_contenedor_paginas)


        self.horizontalLayout_17.addWidget(self.paginas)

        self.frame_22 = QFrame(self.frm_centrado)
        self.frame_22.setObjectName(u"frame_22")
        self.frame_22.setMaximumSize(QSize(1, 1))
        self.frame_22.setFrameShape(QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_18 = QHBoxLayout(self.frame_22)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.frm_costad_limite = QFrame(self.frame_22)
        self.frm_costad_limite.setObjectName(u"frm_costad_limite")
        self.frm_costad_limite.setMaximumSize(QSize(1, 16777215))
        self.frm_costad_limite.setFrameShape(QFrame.StyledPanel)
        self.frm_costad_limite.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_18.addWidget(self.frm_costad_limite)


        self.horizontalLayout_17.addWidget(self.frame_22)


        self.horizontalLayout_8.addWidget(self.frm_centrado)


        self.verticalLayout.addWidget(self.frm_centro)

        self.frm_pie = QFrame(self.frm_contenedor_cuerpo)
        self.frm_pie.setObjectName(u"frm_pie")
        self.frm_pie.setMaximumSize(QSize(16777215, 50))
        self.frm_pie.setFrameShape(QFrame.StyledPanel)
        self.frm_pie.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_10 = QHBoxLayout(self.frm_pie)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.frm_pie_interno = QWidget(self.frm_pie)
        self.frm_pie_interno.setObjectName(u"frm_pie_interno")

        self.horizontalLayout_10.addWidget(self.frm_pie_interno)

        self.Qzise = QWidget(self.frm_pie)
        self.Qzise.setObjectName(u"Qzise")
        self.Qzise.setMinimumSize(QSize(10, 10))
        self.Qzise.setMaximumSize(QSize(10, 10))

        self.horizontalLayout_10.addWidget(self.Qzise, 0, Qt.AlignRight|Qt.AlignBottom)


        self.verticalLayout.addWidget(self.frm_pie)

        self.frm_pie.raise_()
        self.frm_centro.raise_()
        self.frm_cabecera.raise_()

        self.horizontalLayout.addWidget(self.frm_contenedor_cuerpo)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stw_contenedor_paginas.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_home.setText("")
        self.btn_add.setText("")
        self.btn_gestion.setText("")
        self.btn_desplegar.setText("")
        self.btn_minii.setText("")
        self.btn_cerrarr.setText("")
        self.btn_agregar_desplegable.setText(QCoreApplication.translate("MainWindow", u"Agr. Alumno", None))
#if QT_CONFIG(accessibility)
        self.btn_agregar_desplegable_docente.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(accessibility)
        self.btn_agregar_desplegable_docente.setText(QCoreApplication.translate("MainWindow", u"Agr. Docente", None))
        self.btn_gestionar_alumnos_desplegable.setText(QCoreApplication.translate("MainWindow", u"Ges. Alumnos", None))
        self.btn_gestionar_docentes_desplegable.setText(QCoreApplication.translate("MainWindow", u"Ges. Docentes", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; text-decoration: underline;\">Kame-senryu</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.frame_58.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/icons/icons/titulo_agregar_estudiantes.PNG\"/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Nombre/s:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Documento:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Apellidos:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Telefono:", None))
        self.rb_hombre_estudiantes.setText(QCoreApplication.translate("MainWindow", u"Hombre", None))
        self.rb_mujer_estudiantes.setText(QCoreApplication.translate("MainWindow", u"Mujer", None))
        self.btn_cancelar_estudiantes.setText(QCoreApplication.translate("MainWindow", u"Cancelar", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Grado:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Sexo:", None))
        self.btn_guardar_estudiantes.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
        self.cbx_grado_estudiantes.setItemText(0, QCoreApplication.translate("MainWindow", u"Primero", None))
        self.cbx_grado_estudiantes.setItemText(1, QCoreApplication.translate("MainWindow", u"Segundo", None))
        self.cbx_grado_estudiantes.setItemText(2, QCoreApplication.translate("MainWindow", u"Tercero", None))
        self.cbx_grado_estudiantes.setItemText(3, QCoreApplication.translate("MainWindow", u"Cuarto", None))
        self.cbx_grado_estudiantes.setItemText(4, QCoreApplication.translate("MainWindow", u"Quinto", None))
        self.cbx_grado_estudiantes.setItemText(5, QCoreApplication.translate("MainWindow", u"Sexto", None))
        self.cbx_grado_estudiantes.setItemText(6, QCoreApplication.translate("MainWindow", u"Septimo", None))
        self.cbx_grado_estudiantes.setItemText(7, QCoreApplication.translate("MainWindow", u"Octavo", None))
        self.cbx_grado_estudiantes.setItemText(8, QCoreApplication.translate("MainWindow", u"Noveno", None))
        self.cbx_grado_estudiantes.setItemText(9, QCoreApplication.translate("MainWindow", u"Diez", None))
        self.cbx_grado_estudiantes.setItemText(10, QCoreApplication.translate("MainWindow", u"Once", None))

        self.btn_actualizar_estudiante_2.setText(QCoreApplication.translate("MainWindow", u"Actualizar", None))
        self.btn_buscar_estudiante_2.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Grado:", None))
        self.cbx_edit_grado_doce.setItemText(0, QCoreApplication.translate("MainWindow", u"Primero", None))
        self.cbx_edit_grado_doce.setItemText(1, QCoreApplication.translate("MainWindow", u"Segundo", None))
        self.cbx_edit_grado_doce.setItemText(2, QCoreApplication.translate("MainWindow", u"Tercero", None))
        self.cbx_edit_grado_doce.setItemText(3, QCoreApplication.translate("MainWindow", u"Cuarto", None))
        self.cbx_edit_grado_doce.setItemText(4, QCoreApplication.translate("MainWindow", u"Quinto", None))
        self.cbx_edit_grado_doce.setItemText(5, QCoreApplication.translate("MainWindow", u"Sexto", None))
        self.cbx_edit_grado_doce.setItemText(6, QCoreApplication.translate("MainWindow", u"Septimo", None))
        self.cbx_edit_grado_doce.setItemText(7, QCoreApplication.translate("MainWindow", u"Octavo", None))
        self.cbx_edit_grado_doce.setItemText(8, QCoreApplication.translate("MainWindow", u"Noveno", None))
        self.cbx_edit_grado_doce.setItemText(9, QCoreApplication.translate("MainWindow", u"Diez ", None))
        self.cbx_edit_grado_doce.setItemText(10, QCoreApplication.translate("MainWindow", u"Once", None))

        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Materia:", None))
        self.cbx_edit_materia_doce.setItemText(0, QCoreApplication.translate("MainWindow", u"Edu.Fisica", None))
        self.cbx_edit_materia_doce.setItemText(1, QCoreApplication.translate("MainWindow", u"Quimica", None))
        self.cbx_edit_materia_doce.setItemText(2, QCoreApplication.translate("MainWindow", u"Matematica", None))
        self.cbx_edit_materia_doce.setItemText(3, QCoreApplication.translate("MainWindow", u"F\u00edsica", None))
        self.cbx_edit_materia_doce.setItemText(4, QCoreApplication.translate("MainWindow", u"Tecnologia", None))
        self.cbx_edit_materia_doce.setItemText(5, QCoreApplication.translate("MainWindow", u"Espa\u00f1ol", None))
        self.cbx_edit_materia_doce.setItemText(6, QCoreApplication.translate("MainWindow", u"Etica", None))

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Horario: ", None))
        self.btn_buscar_docente.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        ___qtablewidgetitem = self.tbl_info_docente.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"ID", None));
        ___qtablewidgetitem1 = self.tbl_info_docente.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Nombre", None));
        ___qtablewidgetitem2 = self.tbl_info_docente.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Apellido", None));
        self.btn_guardar_docente_2.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
        self.btn_eliminar_docente.setText(QCoreApplication.translate("MainWindow", u"Eliminar", None))
        self.btn_buscar_estudiante.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        ___qtablewidgetitem3 = self.tbl_info_estudiante.horizontalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"ID", None));
        ___qtablewidgetitem4 = self.tbl_info_estudiante.horizontalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Nombre", None));
        ___qtablewidgetitem5 = self.tbl_info_estudiante.horizontalHeaderItem(2)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Apellido", None));
        self.btn_guardar_estudiantes_ges.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
        self.btn_eliminar_estudiante_ges.setText(QCoreApplication.translate("MainWindow", u"Eliminar", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Nota final:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Grado:", None))
        self.cbx_edit_grado_est.setItemText(0, QCoreApplication.translate("MainWindow", u"Primero", None))
        self.cbx_edit_grado_est.setItemText(1, QCoreApplication.translate("MainWindow", u"Segundo", None))
        self.cbx_edit_grado_est.setItemText(2, QCoreApplication.translate("MainWindow", u"Tercero", None))
        self.cbx_edit_grado_est.setItemText(3, QCoreApplication.translate("MainWindow", u"Cuarto", None))
        self.cbx_edit_grado_est.setItemText(4, QCoreApplication.translate("MainWindow", u"Quinto", None))
        self.cbx_edit_grado_est.setItemText(5, QCoreApplication.translate("MainWindow", u"Sexto", None))
        self.cbx_edit_grado_est.setItemText(6, QCoreApplication.translate("MainWindow", u"Septimo", None))
        self.cbx_edit_grado_est.setItemText(7, QCoreApplication.translate("MainWindow", u"Octavo", None))
        self.cbx_edit_grado_est.setItemText(8, QCoreApplication.translate("MainWindow", u"Noveno", None))
        self.cbx_edit_grado_est.setItemText(9, QCoreApplication.translate("MainWindow", u"Diez ", None))
        self.cbx_edit_grado_est.setItemText(10, QCoreApplication.translate("MainWindow", u"Once", None))

        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Periodo:", None))
        self.cbx_edit_periodo_est.setItemText(0, QCoreApplication.translate("MainWindow", u"Primero", None))
        self.cbx_edit_periodo_est.setItemText(1, QCoreApplication.translate("MainWindow", u"Segundo", None))
        self.cbx_edit_periodo_est.setItemText(2, QCoreApplication.translate("MainWindow", u"Tercero", None))
        self.cbx_edit_periodo_est.setItemText(3, QCoreApplication.translate("MainWindow", u"Cuarto", None))

        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Materia:", None))
        self.cbx_edit_materia_est.setItemText(0, QCoreApplication.translate("MainWindow", u"Edu.Fisica", None))
        self.cbx_edit_materia_est.setItemText(1, QCoreApplication.translate("MainWindow", u"Quimica", None))
        self.cbx_edit_materia_est.setItemText(2, QCoreApplication.translate("MainWindow", u"Matematica", None))
        self.cbx_edit_materia_est.setItemText(3, QCoreApplication.translate("MainWindow", u"F\u00edsica", None))
        self.cbx_edit_materia_est.setItemText(4, QCoreApplication.translate("MainWindow", u"Tecnologia", None))
        self.cbx_edit_materia_est.setItemText(5, QCoreApplication.translate("MainWindow", u"Espa\u00f1ol", None))
        self.cbx_edit_materia_est.setItemText(6, QCoreApplication.translate("MainWindow", u"Etica", None))

        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Agregar Docente", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Nombre/s:", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Documento:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Apellidos:", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Telefono:", None))
        self.rb_hombre_docente.setText(QCoreApplication.translate("MainWindow", u"Hombre", None))
        self.rb_mujer_docente.setText(QCoreApplication.translate("MainWindow", u"Mujer", None))
        self.btn_cancelar_docente.setText(QCoreApplication.translate("MainWindow", u"Cancelar", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Sexo:", None))
        self.btn_guardar_docente.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
        self.btn_actualizar_docente.setText(QCoreApplication.translate("MainWindow", u"Actualizar", None))
        self.btn_buscar_docente_2.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
    # retranslateUi

